### ISSUE TITLE
关于，蓝桥杯第二次模拟赛题目

### ISSUE THREAD

**Issue by jingsongliujing** [PlutoaCharon/LanQiaoCode_Python#5]
你好，这是我们参加蓝桥杯第二次模拟赛题目，因为本人水平有限，只有两三题能全部通过测试，所以我附上了全部题目，希望大佬能把剩下的几题也更新出来，由于我权限有限，但我希望自己也能为这个项目添砖加瓦，谢谢

**Comment by PlutoaCharon** [comment]
我把我的省赛模拟做题记录已经上传到仓库中了 你可以参考一下, 里面也给了我博客讲解的链接
